[target.x86_64-unknown-none]
rustflags = [
    "-Crelocation-model=static",
    "-Clink-arg=-Tlinker.ld",
    "-Clink-arg=--no-dynamic-linker",
    "-Clink-arg=--no-pie",
    "-Clink-arg=--omagic",
    "-Clink-arg=-nostartfiles",
    "-Clink-arg=-nostdlib",
]